import os
import io
import datetime
import pandas as pd
from typing import Dict, Any, Optional
from fpdf import FPDF
from tools.business_tools import load_data, get_sales_summary, get_inventory_summary, get_finance_summary
from utils.logger import logger

# Create a reports output directory
REPORTS_DIR = "reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

class BusinessReportPDF(FPDF):
    def header(self):
        # Arial bold
        self.set_font('Helvetica', 'B', 15)
        # Title
        self.cell(0, 10, 'BizPilot AI - Business Operations Report', 0, 1, 'C')
        # Line break
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Helvetica', 'I', 8)
        # Page number
        self.cell(0, 10, f'Page {self.page_no()} | Generated by BizPilot AI on {datetime.date.today()}', 0, 0, 'C')

def generate_pdf_report(summary_data: Dict[str, Any]) -> str:
    """
    Generate a clean PDF report summarizing business operations.
    Returns the path to the generated PDF file.
    """
    try:
        pdf = BusinessReportPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_font('Helvetica', '', 12)
        
        # Date & Intro
        pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
        pdf.cell(0, 10, f"Business Health Score: {summary_data.get('health_score', 'N/A')}/100", 0, 1)
        pdf.ln(5)
        
        # Executive Summary
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, "Executive Summary", 0, 1)
        pdf.set_font('Helvetica', '', 11)
        pdf.multi_cell(190, 7, summary_data.get("summary", "No summary provided."))
        pdf.ln(5)
        
        # Sales Section
        sales = get_sales_summary()
        if sales.get("status") == "success":
            pdf.set_font('Helvetica', 'B', 14)
            pdf.cell(0, 10, "1. Sales Analysis", 0, 1)
            pdf.set_font('Helvetica', '', 11)
            pdf.cell(0, 7, f"Total Revenue: ${sales.get('total_revenue', 0.0):,.2f}", 0, 1)
            pdf.cell(0, 7, f"Total Items Sold: {sales.get('total_items_sold', 0):,}", 0, 1)
            
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(0, 7, "Top Products (by revenue):", 0, 1)
            pdf.set_font('Helvetica', '', 11)
            for prod in sales.get("top_products", []):
                pdf.cell(0, 7, f" - {prod['product']}: ${prod['amount']:,.2f}", 0, 1)
            pdf.ln(5)

        # Inventory Section
        inventory = get_inventory_summary()
        if inventory.get("status") == "success":
            pdf.set_font('Helvetica', 'B', 14)
            pdf.cell(0, 10, "2. Inventory Status", 0, 1)
            pdf.set_font('Helvetica', '', 11)
            pdf.cell(0, 7, f"Total Stock Valuation: ${inventory.get('total_valuation', 0.0):,.2f}", 0, 1)
            pdf.cell(0, 7, f"Total Stock Items: {inventory.get('total_items', 0):,}", 0, 1)
            pdf.cell(0, 7, f"Items Needing Reorder: {len(inventory.get('low_stock_items', []))}", 0, 1)
            pdf.ln(5)
            
        # Finance Section
        finance = get_finance_summary()
        if finance.get("status") == "success":
            pdf.set_font('Helvetica', 'B', 14)
            pdf.cell(0, 10, "3. Financial Overview", 0, 1)
            pdf.set_font('Helvetica', '', 11)
            pdf.cell(0, 7, f"Total Sales Revenue: ${finance.get('total_revenue', 0.0):,.2f}", 0, 1)
            pdf.cell(0, 7, f"Total Expenses: ${finance.get('total_expenses', 0.0):,.2f}", 0, 1)
            pdf.cell(0, 7, f"Net Profit: ${finance.get('net_profit', 0.0):,.2f}", 0, 1)
            pdf.cell(0, 7, f"Net Margin: {finance.get('profit_margin', 0.0):.2f}%", 0, 1)
            pdf.ln(5)

        # Recommendations / Action Plan
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, "4. Advisor Recommendations", 0, 1)
        pdf.set_font('Helvetica', '', 11)
        for idx, rec in enumerate(summary_data.get("recommendations", [])):
            pdf.multi_cell(190, 7, f"{idx+1}. {rec}")
            
        filename = f"report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(REPORTS_DIR, filename)
        pdf.output(filepath)
        logger.info(f"Report generated successfully: {filepath}")
        return filepath
    except Exception as e:
        logger.error(f"Error generating PDF report: {e}")
        return ""

def export_excel_report() -> str:
    """
    Consolidate all business data sheets into a single structured Excel report.
    Returns the path to the generated Excel file.
    """
    try:
        filename = f"business_summary_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        filepath = os.path.join(REPORTS_DIR, filename)
        
        with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
            # 1. Sales
            sales_df = load_data("sales")
            if sales_df is not None:
                sales_df.to_excel(writer, sheet_name="Sales", index=False)
                
            # 2. Inventory
            inventory_df = load_data("inventory")
            if inventory_df is not None:
                inventory_df.to_excel(writer, sheet_name="Inventory", index=False)
                
            # 3. Expenses
            expenses_df = load_data("expenses")
            if expenses_df is not None:
                expenses_df.to_excel(writer, sheet_name="Expenses", index=False)
                
        logger.info(f"Excel report exported successfully: {filepath}")
        return filepath
    except Exception as e:
        logger.error(f"Error exporting Excel report: {e}")
        return ""

def generate_charts(chart_type: str) -> str:
    """
    Generate static PNG charts for the MCP client and return the image file path.
    Supported types: 'sales_trend', 'expense_categories', 'inventory_levels'
    """
    try:
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(8, 5))
        
        if chart_type == "sales_trend":
            sales = get_sales_summary()
            if sales.get("status") == "success" and sales.get("monthly_trends"):
                trends = sales["monthly_trends"]
                months = [t["month_yr"] for t in trends]
                amounts = [t["amount"] for t in trends]
                ax.plot(months, amounts, marker='o', color='#1E88E5', linewidth=2)
                ax.set_title("Monthly Sales Trend")
                ax.set_ylabel("Revenue ($)")
                ax.grid(True, linestyle='--', alpha=0.6)
            else:
                ax.text(0.5, 0.5, "No sales data available", ha='center', va='center')
                
        elif chart_type == "expense_categories":
            finance = get_finance_summary()
            if finance.get("status") == "success" and finance.get("expenses_by_category"):
                cats = finance["expenses_by_category"]
                labels = [c["category"] for c in cats]
                values = [c["amount"] for c in cats]
                ax.pie(values, labels=labels, autopct='%1.1f%%', startangle=90, colors=['#E53935', '#FB8C00', '#FDD835', '#43A047', '#1E88E5', '#8E24AA'])
                ax.set_title("Expenses by Category")
            else:
                ax.text(0.5, 0.5, "No expense data available", ha='center', va='center')
                
        elif chart_type == "inventory_levels":
            inventory = get_inventory_summary()
            if inventory.get("status") == "success" and inventory.get("low_stock_items"):
                items = inventory["low_stock_items"][:10] # Top 10 low stock items
                products = [i["product"] for i in items]
                levels = [i["stocklevel"] for i in items]
                ax.barh(products, levels, color='#FFB300')
                ax.set_title("Current Stock Levels (Low Stock Items)")
                ax.set_xlabel("Quantity")
            else:
                ax.text(0.5, 0.5, "No low-stock items detected", ha='center', va='center')
        
        plt.tight_layout()
        chart_filename = f"chart_{chart_type}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        chart_path = os.path.join(REPORTS_DIR, chart_filename)
        plt.savefig(chart_path)
        plt.close()
        return chart_path
    except Exception as e:
        logger.error(f"Error generating chart {chart_type}: {e}")
        return ""
